# Generated by Django 4.2 on 2023-06-21 07:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_review_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=8, max_length=8, verbose_name='Id')),
                ('order_stuts', models.CharField(choices=[('Recieved', 'Recieved'), ('Processod', 'Processod'), ('Shipped', 'Shipped'), ('Deliverod', 'Recieved')], max_length=50, verbose_name='Order Stuts')),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Time')),
                ('deliver_time', models.DateTimeField(blank=True, null=True, verbose_name='Deliver Time')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDateil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('quantite', models.FloatField(verbose_name='Quantite')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product', to='products.product', verbose_name='Product')),
            ],
        ),
    ]
