# Generated by Django 4.2 on 2023-06-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdateil',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_dateil', to='orders.order', verbose_name='Order Dateil'),
        ),
    ]
